name: Codacy Coverage Reporter
on: 
  push:
    branches: 
      - master

jobs:
  codacy_coverage_reporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
